### ISSUE TITLE
Error in library(Rcrypt) : there is no package called ‘Rcrypt’

### ISSUE THREAD

**Issue by borexino** [enginestein/Rcrypt#1]
```
> library(Rcrypt)
Error in library(Rcrypt) : there is no package called ‘Rcrypt’
> devtools::install_github("enginestein/Rcrypt")
Skipping install of 'rcrypt' from a github remote, the SHA1 (c6985a14) has not changed since last install.
  Use `force = TRUE` to force installation
> library(Rcrypt)
Error in library(Rcrypt) : there is no package called ‘Rcrypt’
> library(rcrypt)
```

Note `Rcrypt` vs `rcrypt`

**Comment by enginestein** [comment]
Hello

It looks like you are importing **Rcrypt** before installing it.  You should first use the `devtools::install_github("enginestein/Rcrypt")` function and then import it using `library(Rcrypt)` if it still does not work try using `githubinstall` function. If it still does not work you should clone the repository and use functions from `public_api.r`. If it still does not work, then inform me and I will fix it.

**Comment by enginestein** [comment]
Closing this issue because of no further activity, please open a new issue if there is a bug in the code.
